; EnemyOne.inc : 種類別のエネミー
;


; マクロの定義
;

; なし

; 外部関数宣言
;

    .globl  _EnemyNull
    .globl  _EnemyBomb
    .globl  _EnemyBoss
    .globl  _EnemyBossRender
    .globl  _EnemyI
    .globl  _EnemyN
    .globl  _EnemyS
    .globl  _EnemyJ

; 外部変数宣言
;

    .globl  _enemyNullDefault
    .globl  _enemyBombDefault
    .globl  _enemyBossDefault
    .globl  _enemyIDefault
    .globl  _enemyNDefault
    .globl  _enemySDefault
    .globl  _enemyJDefault
